/**
 * Staged deploy for exchange.compact when the full 13-circuit deploy
 * transaction is too large for a network's block-weight limit.
 *
 * Background: `npm run deploy` submits ONE transaction that registers every
 * exported circuit's verifier key. With the Treasury module, that's grown to
 * 13 circuits, and both the local devnet AND Preprod reject that transaction
 * outright with `1010: Invalid Transaction: Transaction would exhaust the
 * block limits` (see scripts/e2e-check.ts's doc comment for the local-devnet
 * instance of this; this script exists because the same thing happens on a
 * real public network too, contradicting that comment's assumption that a
 * "real" block-weight limit would be large enough).
 *
 * Fix: Midnight supports adding a circuit's verifier key to an already-
 * deployed contract via a separate "maintenance" transaction
 * (submitInsertVerifierKeyTx), signed by the contract's maintenance
 * authority (CMA) — a signing key `deployContract` automatically samples and
 * stores in the private-state provider, keyed by contract address, when the
 * deploy doesn't supply one explicitly (see @midnight-ntwrk/midnight-js-
 * contracts' deploy-contract.d.ts). So: deploy a REDUCED build (the 5
 * original, previously-proven-to-fit circuits: createOrder/getOrder/
 * cancelOrder/expireOrder/settle, plus the 3 zero-cost pure circuits) using
 * the SAME wallet/private-state provider this script runs with, then insert
 * each of the 8 Treasury/PPM circuits' verifier keys one at a time,
 * immediately afterward, in the same process — the CMA key never leaves the
 * private-state provider it was generated into.
 *
 * The reduced ("stage 1") build is generated by truncating
 * contracts/exchange.compact right after settle()'s closing brace (before
 * "Module 5: Treasury"), so every ledger/struct/enum/witness declaration —
 * and therefore the deployed contract's on-chain layout — is byte-for-byte
 * identical to what a (hypothetical, too-large) single-transaction deploy of
 * the full contract would have produced. Only the *order* in which circuits
 * become callable differs: the 8 Treasury/PPM circuits are unusable for the
 * few seconds between stage 1's deploy and stage 2's last insert.
 *
 * Usage: STAGE1_SOURCE must point at a pre-compiled reduced build (see
 * scratch generation in this session's transcript, or regenerate: take
 * contracts/exchange.compact up to and including settle()'s closing `}`,
 * compile it to a scratch directory with `compact compile`). This script
 * does not regenerate it itself, to avoid silently drifting from whatever
 * exact circuit split was actually used for a given deploy — regenerate and
 * point at it deliberately.
 *
 *   STAGE1_ZK_PATH=/path/to/scratch/managed npx tsx scripts/deploy-staged.ts --network preprod
 */
import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { WebSocket } from 'ws';
import * as Rx from 'rxjs';

import { resolveNetwork, getOrCreateSeed, getOrCreateAdminSecret, recordDeployment } from '../src/network.js';
import { createWallet, persistWalletState, unshieldedToken } from '../src/wallet.js';

import { deployContract, submitInsertVerifierKeyTx } from '@midnight-ntwrk/midnight-js-contracts';
import { httpClientProofProvider } from '@midnight-ntwrk/midnight-js-http-client-proof-provider';
import { indexerPublicDataProvider } from '@midnight-ntwrk/midnight-js-indexer-public-data-provider';
import { levelPrivateStateProvider } from '@midnight-ntwrk/midnight-js-level-private-state-provider';
import { NodeZkConfigProvider } from '@midnight-ntwrk/midnight-js-node-zk-config-provider';
import { CompiledContract } from '@midnight-ntwrk/compact-js';

// @ts-expect-error Required for wallet sync
globalThis.WebSocket = WebSocket;

const STAGE1_ZK_PATH = process.env.STAGE1_ZK_PATH;
if (!STAGE1_ZK_PATH) {
  console.error('\n❌ Set STAGE1_ZK_PATH to a pre-compiled reduced-circuit build (see this file\'s doc comment).\n');
  process.exit(1);
}

// The 8 circuits deliberately left out of the stage-1 build, in the order
// they'll be inserted. Order doesn't matter functionally (each insert is
// independent), kept in source order for readability of the deploy log.
const STAGE2_CIRCUITS = [
  'addAdmin',
  'removeAdmin',
  'depositTreasury',
  'withdrawTreasury',
  'reserveLiquidity',
  'releaseLiquidity',
  'releaseExpiredLiquidity',
  'settleWithProtocol',
] as const;

const { network, config: networkConfig } = resolveNetwork();
const SEED = getOrCreateSeed(network);

async function waitForProofServer(maxAttempts = 60, delayMs = 2000): Promise<boolean> {
  for (let attempt = 1; attempt <= maxAttempts; attempt++) {
    try {
      await fetch(networkConfig.proofServer, { method: 'GET', signal: AbortSignal.timeout(3000) });
      return true;
    } catch (err: any) {
      const code = err?.cause?.code || err?.code || '';
      if (code !== 'ECONNREFUSED' && code !== 'UND_ERR_CONNECT_TIMEOUT' && code !== 'UND_ERR_SOCKET') return true;
    }
    if (attempt < maxAttempts) {
      process.stdout.write(`\r  Waiting for proof server... (${attempt}/${maxAttempts})   `);
      await new Promise((r) => setTimeout(r, delayMs));
    }
  }
  return false;
}

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const fullZkConfigPath = path.resolve(__dirname, '..', 'contracts', 'managed', 'exchange');
const fullContractPath = path.join(fullZkConfigPath, 'contract', 'index.js');
const stage1ContractPath = path.join(STAGE1_ZK_PATH, 'contract', 'index.js');

for (const [label, p] of [['full', fullContractPath], ['stage1', stage1ContractPath]] as const) {
  if (!fs.existsSync(p)) {
    console.error(`\n❌ ${label} compiled contract not found at ${p}\n`);
    process.exit(1);
  }
}

const FullExchange = await import(pathToFileURL(fullContractPath).href);
const Stage1Exchange = await import(pathToFileURL(stage1ContractPath).href);

// Deployment never executes a circuit (only the constructor), so these are
// never actually invoked — mirrors src/deploy.ts exactly.
const witnessStubs = {
  orderDetails: () => { throw new Error('orderDetails witness not implemented (deployment does not execute circuits).'); },
  orderBlinding: () => { throw new Error('orderBlinding witness not implemented (deployment does not execute circuits).'); },
  ownerSecretKey: () => { throw new Error('ownerSecretKey witness not implemented (deployment does not execute circuits).'); },
  adminSecretKey: () => { throw new Error('adminSecretKey witness not implemented (deployment does not execute circuits).'); },
};

const adminSecretHex = getOrCreateAdminSecret(network);
const initialAdminId: Uint8Array = FullExchange.pureCircuits.deriveAdminId(Buffer.from(adminSecretHex, 'hex'));

const stage1Compiled = CompiledContract.withCompiledFileAssets(
  CompiledContract.withWitnesses(CompiledContract.make('exchange-stage1', Stage1Exchange.Contract), witnessStubs),
  STAGE1_ZK_PATH,
);
const fullCompiled = CompiledContract.withCompiledFileAssets(
  CompiledContract.withWitnesses(CompiledContract.make('exchange', FullExchange.Contract), witnessStubs),
  fullZkConfigPath,
);

async function createProviders(walletCtx: Awaited<ReturnType<typeof createWallet>>) {
  const privateStatePassword = process.env.PRIVATE_STATE_PASSWORD?.trim() || 'Local-Devnet-Development-Placeholder-1';
  const state = await walletCtx.wallet.waitForSyncedState();

  const walletProvider = {
    getCoinPublicKey: () => state.shielded.coinPublicKey.toHexString(),
    getEncryptionPublicKey: () => state.shielded.encryptionPublicKey.toHexString(),
    async balanceTx(tx: any, ttl?: Date) {
      const recipe = await walletCtx.wallet.balanceUnboundTransaction(
        tx,
        { shieldedSecretKeys: walletCtx.shieldedSecretKeys, dustSecretKey: walletCtx.dustSecretKey },
        { ttl: ttl ?? new Date(Date.now() + 30 * 60 * 1000) },
      );
      const signedRecipe = await walletCtx.wallet.signRecipe(recipe, (payload) => walletCtx.unshieldedKeystore.signData(payload));
      return walletCtx.wallet.finalizeRecipe(signedRecipe);
    },
    submitTx: (tx: any) => walletCtx.wallet.submitTransaction(tx) as any,
  };

  const zkConfigProvider = new NodeZkConfigProvider(fullZkConfigPath);
  const accountId = walletCtx.unshieldedKeystore.getBech32Address().toString();

  return {
    privateStateProvider: levelPrivateStateProvider({
      privateStateStoreName: 'exchange-state',
      accountId,
      privateStoragePasswordProvider: () => privateStatePassword,
    }),
    publicDataProvider: indexerPublicDataProvider(networkConfig.indexer, networkConfig.indexerWS),
    zkConfigProvider,
    proofProvider: httpClientProofProvider(networkConfig.proofServer, zkConfigProvider),
    walletProvider,
    midnightProvider: walletProvider,
  };
}

async function main() {
  console.log('\n╔══════════════════════════════════════════════════════════════╗');
  console.log(`║  Staged deploy of Zekura exchange to ${network}`);
  console.log('╚══════════════════════════════════════════════════════════════╝\n');

  console.log('─── Wallet setup ───────────────────────────────────────────────\n');
  const walletCtx = await createWallet({ network, networkConfig, seed: SEED });
  console.log('  Syncing with network...');
  await walletCtx.wallet.waitForSyncedState();
  console.log('  ✓ Synced.\n');
  await persistWalletState(network, walletCtx);

  console.log('  Checking proof server...');
  if (!(await waitForProofServer())) {
    console.error('\n❌ Proof server not responding.\n');
    await walletCtx.wallet.stop();
    process.exit(1);
  }
  console.log('  Proof server ready.\n');

  const providers = await createProviders(walletCtx);

  console.log('─── Stage 1: deploy reduced (5-circuit) build ─────────────────\n');
  const deployed = await deployContract(providers as any, {
    compiledContract: stage1Compiled as any,
    args: [initialAdminId],
  });
  const contractAddress = deployed.deployTxData.public.contractAddress;
  console.log(`  ✅ Stage 1 deployed: ${contractAddress}\n`);

  console.log('─── Stage 2: insert remaining 8 circuits one at a time ────────\n');
  const fullZk = new NodeZkConfigProvider(fullZkConfigPath);
  for (const circuitId of STAGE2_CIRCUITS) {
    process.stdout.write(`  Inserting ${circuitId}... `);
    const vk = await fullZk.getVerifierKey(circuitId as any);
    try {
      const result = await submitInsertVerifierKeyTx(
        providers as any,
        fullCompiled as any,
        contractAddress,
        circuitId as any,
        vk,
      );
      console.log(`ok (tx ${result.txId})`);
    } catch (err) {
      console.log('FAILED');
      console.error(err);
      console.error(`\n❌ Stopped after failing to insert '${circuitId}'. Contract address ${contractAddress} is`);
      console.error('   partially staged — re-run with the same STAGE1_ZK_PATH to resume (circuits already');
      console.error('   inserted are skipped by submitInsertVerifierKeyTx\'s own "already defined" check... no,');
      console.error('   it throws for already-defined circuits — remove already-inserted names from');
      console.error('   STAGE2_CIRCUITS above before re-running, or insert the remainder by hand.\n');
      await walletCtx.wallet.stop();
      process.exit(1);
    }
  }

  recordDeployment(network, contractAddress, walletCtx.unshieldedKeystore.getBech32Address().toString());
  console.log(`\n✅ All 13 circuits live at ${contractAddress}. Saved to .midnight-state.json.\n`);

  await persistWalletState(network, walletCtx);
  await walletCtx.wallet.stop();
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
